USE [master]
GO

/****** Object:  Database [DB_TesteTarefas]    Script Date: 13/07/2024 12:58:16 ******/
CREATE DATABASE [DB_TesteTarefas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_TesteTarefas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DB_TesteTarefas.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_TesteTarefas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DB_TesteTarefas_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_TesteTarefas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_TesteTarefas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_TesteTarefas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_TesteTarefas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DB_TesteTarefas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_TesteTarefas] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DB_TesteTarefas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_TesteTarefas] SET  MULTI_USER 
GO

ALTER DATABASE [DB_TesteTarefas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_TesteTarefas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_TesteTarefas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_TesteTarefas] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_TesteTarefas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_TesteTarefas] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DB_TesteTarefas] SET QUERY_STORE = ON
GO

ALTER DATABASE [DB_TesteTarefas] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DB_TesteTarefas] SET  READ_WRITE 
GO


